# Generated by Django 2.1.2 on 2018-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='Hero_bg',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
    ]
