# Generated by Django 2.1.2 on 2018-12-07 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181207_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Video_Hero',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='main.Hero'),
            preserve_default=False,
        ),
    ]
