# Generated by Django 2.1.2 on 2018-12-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video_video_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Video_Hero',
        ),
        migrations.AlterField(
            model_name='video',
            name='Video_url',
            field=models.CharField(max_length=200),
        ),
    ]
