# Generated by Django 2.1.2 on 2018-12-07 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181208_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Video_Hero',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.Hero'),
            preserve_default=False,
        ),
    ]
