# Generated by Django 2.1.2 on 2018-12-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_video_video_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Hero_name',
            field=models.CharField(default=324, max_length=25),
            preserve_default=False,
        ),
    ]
