# Generated by Django 2.1.2 on 2018-12-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181208_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Video_hero',
        ),
    ]
