# Generated by Django 2.1.2 on 2018-12-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_video_video_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_text',
            field=models.TextField(verbose_name='Введите текст'),
        ),
    ]
